nodes:
  - id: 1
    name: Start
    plugin: default
    type: trigger
    parameters: {}

  - id: 2
    name: Fetch Data
    plugin: http
    type: action
    parameters:
      url: "https://httpbin.org/status/503"
      method: GET
      headers:
        Authorization: "Bearer {{ token }}"

  - id: 3
    name: Send Data
    plugin: http
    type: action
    parameters:
      url: "http://httpbin.org/post"
      method: POST
      data:
        format: json
        raw_message: "raw message"
        form_parameters:
          - key1: value1
          - key2: value2
        json_message: '{"key1": "value1", "key2": 20}'
      headers:
        Authorization: "Bearer {{ token }}"

connections:
  "1":
    - to: 2
  "2":
    - to: 3