nodes:
  - id: 1
    name: Start
    plugin: default
    type: trigger
    parameters: {}

  - id: 2
    name: Fetch Data
    plugin: http
    type: action
    parameters:
      url: "https://httpbin.org/basic-auth/user/pass"
      method: GET
      basic_auth:
          username: user
          password: pass

  - id: 3
    name: Send Data
    plugin: http
    type: action
    parameters:
      url: "http://httpbin.org/post"
      method: POST
      data:
        format: json
        raw_message: "raw message"
        form_parameters:
          - key1: value1
          - key2: value2
        json_message: '{"key1": "value1", "key2": 20}'
      bearer_auth: my_token
      headers:
        - Content-Type: application/json
        - Accept: application/json
        - Host: httpbin.org
        

connections:
  "1":
    - to: 2
  "2":
    - to: 3